version: "3.8"
services:
  go:
    build: ./go
    tty: true
    ports:
      - '8080:8080'
  react:
    build: ./react
    tty: true
    ports:
      - 3000:3000
  db:
    build: ./db
    tty: true
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306